### ISSUE TITLE
IOS is not working on Mac 15.5 (Seqouia)

### ISSUE THREAD

**Issue by smswebby** [flexn-io/renative#1878]
**Describe the bug**
The iOS build process for the React Native project fails with multiple issues:
	•	Warnings from Watchman (watch-project and query) about recrawling due to MustScanSubDirs and UserDropped.
	•	An error during the compilation phase indicating an implicit instantiation of undefined template std::char_traits<fmt::internal::char8_type>, likely stemming from fmt library usage.
	•	Build failures citing explicit and implicit dependencies not resolved correctly in the Pods project during linking.

**To Reproduce**
	1.	Run npx rnv run -p ios in the project directory.
	2.	Select a simulator (e.g., iPhone 15 Pro).
	3.	Observe build process logs and errors during linking and compilation.

**Expected behavior**
The build should complete successfully with no dependency resolution errors, Watchman warnings, or compilation errors related to the fmt library.

**Screenshots or copy&paste**
Here’s a relevant snippet from the error log:
error: implicit instantiation of undefined template 'std::char_traits<fmt::internal::char8_type>'
 378 | : data_(s), size_(std::char_traits<Char>::length(s)) {}
   | ^

Additionally, numerous Watchman warnings:
WARN  Watchman `watch-project` returned a warning: Recrawled this watch 31 times, most recently because:
MustScanSubDirs UserDroppedTo resolve, please review the information on
https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl

**Desktop (please complete the following information):**
-   OS:  Mac 15.5 (Seqouia)
-   Node Version: v18.20.2
-   RNV Version: 1.9.1

**Additional context**
	•	This issue seems tied to an incomplete or broken Pod dependency resolution, as evidenced by multiple implicit and explicit linking errors in the Pods project.
	•	The fmt library (used for formatting) is causing a compilation failure due to missing char_traits for char8_type. This may be due to a missing header or an incompatibility with the compiler version or C++ standard being used.
	•	Watchman warnings suggest filesystem scan issues or misconfigurations, potentially causing unnecessary rebuilds or slowdowns.
	•	Project may need updates for compatibility with React Native 0.73 and its changes to Metro configuration.
